name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-18.04

    steps:
    - name: Set up qemu-user-static
      run: |
        sudo apt-get update && sudo apt-get install -yq qemu binfmt-support qemu-user-static
        docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
        docker run --rm -t arm64v8/ubuntu uname -m
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag hmahadik/streamproc-development:$(date +%s)
